### ISSUE TITLE
Created by device id

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapfilter-db#102]
Right now if you create an element/obs on one device, and then edit it on another device, it's difficult and/or impossible to figure out who was the original creator of the element/obs because the device id changes to the latest edit, not of the creator. 

It might be nice to have multiple fields, one for creator and one for editor.

We can create an additional index and send a virtual field.

**Comment by hackergrrl** [comment]
@okdistribute What feature does this support? Also, any ideas on timeline & urgency?

**Comment by okdistribute** [comment]
@noffle we discussed this in the morning.. no idea about urgency but I imagine by the next mapeo release late aug

**Comment by okdistribute** [comment]
The use case is that the mobile app currently prevents users from editing observations that they didn't create; but the field reflects who last edited it, not who created it originally.

**Comment by hackergrrl** [comment]
@okdistribute Thanks for refreshing me!

**Comment by gmaclennan** [comment]
@okdistribute just surfacing this again. I don't think it's urgent, but at some point it will crop up for users and be frustrating. We should review this for October's priorities and decide when to add it.

**Comment by okdistribute** [comment]
@gmaclennan I agree; after I get Md 5.4 out the door we can discuss
