### ISSUE TITLE
(Back) Research SQL

### ISSUE THREAD

**Issue by ErikSin** [digidem/mapfilter-db#129]
As an alternative to Realm, we can research the SQLlite.

We need to determine if we can write our hypercore data to SQL.

Questions to answer

Points : 13 points

**Comment by achou11** [comment]
Can we close this considering that gregor got realm compiling on mobile?

**Comment by ErikSin** [comment]
> Can we close this considering that gregor got realm compiling on mobile?

yeyeyeye!!
